### ISSUE TITLE
Make good Readme File

### ISSUE THREAD

**Issue by badal8381** [badal8381/spokentutorial#3]

**Comment by llyram** [comment]
assign this to me

**Comment by Bhavyaseth-afk** [comment]
Hey, I would like to contribute to this
Please see if this issue could be assigned to me

**Comment by Vedant755** [comment]
Hey I'm very much good at writing readme file, I will be concise with the points and provide proper steps to work for developers to know more about your project.

**Comment by badal8381** [comment]
Just do it and create pull request I'll merge it
